version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: Web.Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
    networks:
      - ffh-net

  db:
    image: "postgres:11"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - ffh-net

networks:
  ffh-net:
    driver: bridge