# Generated by Django 3.1.7 on 2021-03-17 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('picture_url', models.CharField(max_length=1000)),
                ('song_url', models.CharField(max_length=1000)),
                ('album', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'song_song',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'song_tag',
            },
        ),
        migrations.CreateModel(
            name='SongTag',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.song')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.tag')),
            ],
            options={
                'db_table': 'song_song_tag',
            },
        ),
    ]
