# Generated by Django 3.1.7 on 2021-03-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210312_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.JSONField(),
        ),
    ]
